// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trzsgpkepzpmtyqalnba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyenNncGtlcHpwbXR5cWFsbmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDc5OTIsImV4cCI6MjA2OTUyMzk5Mn0.6VcYaibvUbAOLn7vY_CYn1zejKuzEKPtKZz87aCxTv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});